### ISSUE TITLE
I encountered this type of error during installation (latest version)

### ISSUE THREAD

**Issue by AnOpenHeresy** [LCA-EET/Lichdom#5]
//[C:\Games\PI\Tools\WeiDU\249.00\weidu.exe] WeiDU version 24900
//Using Language [English]
//Using .\lang\en_us\dialog.tlk
//ERROR: No translation provided for @0
//Continuing despite error.
//Installing [UNDEFINED STRING:   @0]
//ERROR: No translation provided for @1
//Stopping installation because of error.
//Stopping installation because of error.
//ERROR Installing [UNDEFINED STRING:   @0], rolling back to previous state
//Will uninstall   0 files for [lichdom.tp2] component 0.
//Uninstalled      0 files for [lichdom.tp2] component 0.
//ERROR: Not_found
//Please make a backup of the file: Setup-lichdom.debug and look for support at: Daniel Valle, dan@danielvalle.net
//Automatically Skipping [UNDEFINED STRING:   @0] because of error.
//Using Language [English]
//NOT INSTALLED DUE TO ERRORS UNDEFINED STRING:   @0
//WARNING: unpausing installation will continue from next component.
//
//WARNING: lichdom:0 has encounter errors durring installation, exited with ExitCode = 2
[ProjectInfinity-WeiDU-Debug-LCA_Explicit-0.log](https://github.com/LCA-EET/Lichdom/files/14351467/ProjectInfinity-WeiDU-Debug-LCA_Explicit-0.log)
[ProjectInfinity-WeiDU-Debug-lichdom-0.log](https://github.com/LCA-EET/Lichdom/files/14351468/ProjectInfinity-WeiDU-Debug-lichdom-0.log)
[ProjectInfinity-WeiDU-Error-lichdom-0.log](https://github.com/LCA-EET/Lichdom/files/14351469/ProjectInfinity-WeiDU-Error-lichdom-0.log)
[ProjectInfinity-WeiDU-Debug-LCA-0.log](https://github.com/LCA-EET/Lichdom/files/14351470/ProjectInfinity-WeiDU-Debug-LCA-0.log)

**Comment by LCA-EET** [comment]
Hello

Unfortunately, I was unable to duplicate the error you described. On both BG2 EE and EET, the installation succeeded. From the logs you provided, it appears that the issue is with the Lichdom mod, not the LCA_Explicit mod.

Please ensure that you’ve extracted the contents of Install_Lichdom.zip to the directory containing your BG2 EET installation. If a Lichdom folder already exists in that directory, delete it prior to extracting the archive. Once the archive is extracted, run the provided setup file.

Let me know if you run into any further issues.
